#!/bin/sh

sudo -u postgres destroydb bob
sudo -u postgres createdb bob

#
# set up the user table
#
psql bob -f SQL/user_table.sql
psql bob -f SQL/userid_seq.sql

#
# the balances table
#
psql bob -f SQL/balance_table.sql

#
# the messages table
#
psql bob -f SQL/message_table.sql
psql bob -f SQL/msgid_seq.sql

#
# the transactions table
#
psql bob -f SQL/transaction_table.sql

#
# the pwd table
#
psql bob -f SQL/pwd_table.sql

#
# the products table
#
psql bob -f SQL/products_table.sql

#
# the bulk_items table
#
psql bob -f SQL/bulk_items.sql
