#!/usr/bin/expect -f

set timeout 5
set rem_user [lindex $argv 0]
set success 0

if {$rem_user != ""} {
	spawn ssh soda
	expect "*?soda:" { send "psql -U bob\r" }
	expect "bob=>" { send "DELETE FROM users WHERE username = '$rem_user';\r" }
	expect {
		"DELETE 1" { set success 1 }
		"DELETE 0" { set success 2 }
	}
	expect "bob=>" { send "\\q\r" }
	expect "*?soda:" { send "exit\r" }
	if { $success == 1 } {
		send_user "\n\n---> SUCCESS\n\n"
	} elseif { $success == 2 } {
		send_user "\n\n---> FAILED\n\n"
	} else {
		send_user "\n\n---> Something weird happened. Check the database.\n\n"
	}
} else {
	send "The correct usage is: ./rem_user username\n"
}
