---

- name: Install common packages
  apt: pkg={{ item }} state=present
  with_items:
   - chromium-browser
   - slim
   - xinit
  tags:
   - initial
   - kiosk

- name: Create sodaui user
  action: user name=sodaui state=present
  tags:
   - initial
   - kiosk

- name: Deploy sodaui .xinitrc
  sudo: yes
  template: src=xinitrc.j2 dest=/home/sodaui/.xinitrc owner=sodaui group=sodaui
  tags:
   - initial
   - kiosk

- name: Deploy slim.conf
  sudo: yes
  template: src=etc/slim.conf.j2 dest=/etc/slim.conf owner=root group=root mode=0644
  tags:
   - initial
   - kiosk
