#!/bin/bash

CPATH=`readlink -f $0`
MROOT=`dirname ${CPATH}`
cd ${MROOT}

LP=
if [ -f "../lib/firefox-1.5/libxpcom.so" ]; then
	LP=`readlink -f ../lib/firefox-1.5`
else 
	if [ -f "../mozilla/dist/lib/libxpcom.so" ]; then
		LP=`readlink -f ../mozilla/dist/lib`
	else
	    if [ -f "/usr/lib/firefox/libxpcom.so" ]; then
		LP=`readlink -f /usr/lib/firefox`
	    fi
	fi
fi

if [ "${LP}" == "" ]; then
	echo "Error! Can't find libxpcom.so anywhere!"
	exit 2
fi


if [ -f "${LP}/MozKioskBin" ]; then
    MBPATH=${LP}
else if [ -f "./MozKioskBin" ]; then
    MBPATH=`readlink -f .`
else
    echo "Error! Cannot fid MozKioskBin anywhere!"
    exit 3
fi
fi

# without it, the prog crashes for some reason...
cd ${LP}

echo libxpcom at "$LP"
echo mozkoskbin at "$MBPATH"

export LD_LIBRARY_PATH=${LP}
#export LD_AOUT_LIBRARY_PATH=${LP}
echo LD_LIBRARY_PATH=${LD_LIBRARY_PATH} 

# clean up the dirs...

rm -rf ~/.moz-kiosk/ff-profile
mkdir -p ~/.moz-kiosk/ff-profile
cat <<__END__ > ~/.moz-kiosk/ff-profile/prefs.js
user_pref("browser.visited_color",   "#0000EE");
user_pref("keyword.URL", "about:blank");
user_pref("browser.cache.check_doc_frequency",   1);
user_pref("accessibility.typeaheadfind", false);
user_pref("network.protocol-handler.external-default", false);
ruser_pref("browser.formfill.enable", false);
user_pref("update_notifications.enabled", false);
user_pref("network.protocol-handler.external.mailto", false); // for mail
user_pref("network.protocol-handler.external.news", false);   // for news
user_pref("network.protocol-handler.external.snews", false);  // for secure news
user_pref("network.protocol-handler.external.nntp", false);   // also news
user_pref("accessibility.typeaheadfind.autostart", false); 
user_pref("applications.rlogin", ""); 
user_pref("applications.rlogin_with_user", ""); 
user_pref("applications.telnet", ""); 
user_pref("applications.tmp_dir", "");
user_pref("applications.tn3270", ""); 
user_pref("browser.cache.disk.enable", false); 
user_pref("browser.cache.memory.enable", false); 
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_entering_secure.show_once", false);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_entering_weak.show_once", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_leaving_secure.show_once", false);
user_pref("security.warn_submit_insecure", false);
user_pref("security.warn_submit_insecure.show_once", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("security.warn_viewing_mixed.show-once", false);
user_pref("update_notifications.enabled", false);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("browser.urlbar.showPopup", false);
user_pref("browser.urlbar.showSearch", false);

__END__


#exec ldd ./MozKioskBin "$@"
exec ${MBPATH}/MozKioskBin "$@"
