Hi {nickname},

You recently bought something from Chez Bob, and now owe ${debt}. You are thus on the Wall of Shame.

About 95% of our active users aren't on the Wall of Shame. You're now in that last 5% who aren't paying for what they are taking.

Please pay us back as soon as possible. If you need help, just reply to this message.

Thanks very much,
- Chez Bob

PS. We accept credit cards online at https://chezbob.ucsd.edu/payment#{username} !

PPS. See the full list of debtors at https://chezbob.ucsd.edu/wall_of_shame.html

