Hi {nickname},

You've been on Chez Bob's Wall of Shame for the past {days_on_wall} days.

It's important you pay your debt promptly-- staying 'in the black' helps Chez Bob survive.

Please pay us back as soon as possible. If you need help, just reply to this message.

Thanks very much,
- Chez Bob

PS. We accept credit cards online at https://chezbob.ucsd.edu/payment#{username} !

PPS. See the full list of debtors at https://chezbob.ucsd.edu/wall_of_shame.html

