Hi {nickname},

This is just a quick warning: tomorrow we'll be announcing your ongoing Chez Bob debt to the greater community by way of the large display in Chez Bob, the third floor display, and via a public Slack post. To avoid this, please pay off your Chez Bob debt in the next 24 hours.

Thanks very much,
- Chez Bob

PS. We accept credit cards online at https://chezbob.ucsd.edu/payment#{username} !

