#!/bin/bash
#
# Script that should be run periodically (such as from cron) to synchronize
# various finance information in the database and to update financial reports.

CHEZBOB="$HOME/chezbob.hg"

$CHEZBOB/django/chezbob/launch finance_sync >/dev/null
$CHEZBOB/django/chezbob/launch inventory_sync >/dev/null
$CHEZBOB/django/chezbob/launch gnuplot_dump >$HOME/accounts.data
$CHEZBOB/reports/gen-monthly.py <$HOME/accounts.data >$HOME/monthly.data
(cd $HOME; gnuplot $CHEZBOB/reports/finances.gnuplot)
ps2pdf $HOME/finances.ps
