From: Chez Bob <chezbob@cs.ucsd.edu>
Subject: Your Chez Bob Account: %USERNAME%

| Our records indicate that you have an account with Chez Bob, the UCSD
| CSE grad student food co-op, but that you have not used your account
| for at least the past year.

| If you are no longer associated with the department and have no need
| to keep your account open any longer, please let us know so we can
| close it.

| If you'd like to keep the account open, we're happy to do that too.
| If you don't think you'll be using the account right away, a reply is
| appreciated.

| Note that your account currently has a balance of %BALANCE%.  When
| closing your account, you have the option of donating your positive
| balance to Chez Bob.
