From: Chez Bob <chezbob@cs.ucsd.edu>
Subject: Your Chez Bob Account: %USERNAME%

| This is a semi-automated message from Chez Bob, the UCSD CSE grad
| student food co-op.  Our records indicate that you have an account with
| Chez Bob and that this account (%USERNAME%) has a balance of %BALANCE%.

| While we do allow you, for your convenience, to keep a negative balance
| for a short period of time, we do ask that you try to maintain a
| positive account balance.  Money in Chez Bob accounts is used to help
| purchase food and drinks, and accounts with a negative balance make it
| more difficult to keep Chez Bob stocked.  We really appreciate your
| help--by keeping your account balance positive--in keeping Chez Bob
| running.

| If you believe this message to have been sent in error, please contact
| us to help clear up the situation.  You may either reply directly to
| this message, or contact Michael Vrable (mvrable@cs.ucsd.edu), the
| current finance/database manager.  If you are not at UCSD for the summer
| but will be returning in the fall, you needn't do anything now, but do
| please pay off your balance when you return.  If you will not be
| returning to UCSD and wish to make other arrangements to pay off your
| balance, let us know.

--The Chez Bob Team
