From: Chez Bob <chezbob@cs.ucsd.edu>
Subject: Your Chez Bob Account: %USERNAME%

| Our records indicate that you have an account with Chez Bob, the UCSD
| CSE grad student food co-op, and that this account (%USERNAME%) has a
| balance of %BALANCE%.

| While we do allow you, for your convenience, to keep a negative balance
| for a short period of time, we do ask that you try to maintain a
| positive account balance.  Money in Chez Bob accounts is used to help
| purchase food and drinks, and accounts with a negative balance make it
| more difficult to keep Chez Bob stocked.  We really appreciate your
| help--by keeping your account balance positive--in keeping Chez Bob
| running.

| If you believe this message to have been sent in error, please contact
| us (at chezbob@cs.ucsd.edu) to help clear up the situation.  Likewise,
| if you are no longer at UCSD and wish to make other arrangements to pay
| off your balance, let us know.

--The Chez Bob Team
